### ISSUE TITLE
i dosent get suggetions

### ISSUE THREAD

**Issue by VikasGroup** [irtefa/Sym#1]

**Comment by VikasGroup** [comment]
i get only suggesions
but it dosent show perdictions.I get an error in cmd as illegal argument exception

**Comment by VikasGroup** [comment]
i get only suggesions
but it dosent show perdictions.I get an error in cmd as illegal argument exception

**Comment by irtefa** [comment]
@VikasGroup hey man. This is a pretty old project :). Haven't touched it in 3 years!
